
# 数据源配置
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/betta?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: corn
        password: Corn2020!@#
#  redis:
#    host: 192.168.10.100
#    # 端口，默认为6379
#    port: 6379
#    password: 823adf@#!

betta:
  profile: E:/betta/upload
  vueAppBaseApi: /dev-api
server:
  port: 8081

# 日志配置
logging:
  level:
    com.betta: debug